# Generated by Django 5.2 on 2025-05-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_item_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Purchase_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
