# Generated by Django 5.2.1 on 2025-05-28 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts_id', models.CharField(blank=True, max_length=15)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('supply_id', models.CharField(blank=True, max_length=50)),
                ('spec', models.CharField(blank=True, max_length=70)),
                ('production_company', models.CharField(blank=True, max_length=30)),
                ('supply_company', models.CharField(blank=True, max_length=30)),
                ('unit_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('moq_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('purchase_quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('moq', models.CharField(blank=True, max_length=10)),
                ('stock_location', models.CharField(blank=True, max_length=50)),
                ('delivery_date', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'unique_together': {('product', 'item')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='products', through='inventory.ProductMaterial', to='inventory.item'),
        ),
    ]
