# Generated by Django 5.2 on 2025-05-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts_id', models.CharField(blank=True, max_length=15)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('supply_id', models.CharField(blank=True, max_length=50)),
                ('spec', models.CharField(blank=True, max_length=30)),
                ('production_company', models.CharField(blank=True, max_length=30)),
                ('supply_company', models.CharField(blank=True, max_length=30)),
                ('unit_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('moq_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('moq', models.CharField(blank=True, max_length=10)),
                ('delivery_date', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('materials', models.ManyToManyField(blank=True, related_name='products', to='inventory.item')),
            ],
        ),
    ]
