# Generated by Django 5.2 on 2025-05-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterial',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
