# Generated by Django 5.2 on 2025-05-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='spec',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
