# Generated by Django 5.2 on 2025-05-22 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='temp',
        ),
    ]
