# Generated by Django 5.2 on 2025-05-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_purchase_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Purchase_quantity',
            new_name='purchase_quantity',
        ),
    ]
