# Generated by Django 5.2 on 2025-05-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_purchase_quantity_item_purchase_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='spec',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
