# Generated by Django 5.2 on 2025-05-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_squashed_0008_alter_item_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
